sonar.projectKey=siakhooi_collector-to-emulator
sonar.organization=siakhooi

sonar.sources=./src
sonar.tests=./tests

sonar.python.coverage.reportPaths=coverage/coverage-py314.xml
sonar.python.version=3.10,3.11,3.12,3.13,3.14
